In [94]:
import os
import pandas as pd
import matplotlib.pyplot as plt

In [95]:
def get_max_price(symbol):
    tb=pd.read_csv("daily/table_{}.csv".format(symbol),names=["date","sm1","open","high","low","close","volume"])
    return tb["close"].mean(),

In [101]:
def plot_historical(symbol):
    df=pd.read_csv(symbol_to_path(symbol),
                   names=["date","sm1","open","high","low","close","volume"])
    print(df[["high","low"]].head())
    df[["high","low"]].plot()
    plt.show()

In [97]:
def symbol_to_path(symbol, base_dir="data"):
    return os.path.join(base_dir,"table_{}.csv".format(str(symbol)))

In [132]:
def get_base_dataframe(dates):
    df1=pd.DataFrame(index=dates)
    dfSPY=pd.read_csv(symbol_to_path("aapl"),
                      names=["date","sm1","open","high","low","close","volume"],
                      usecols=["date","close"],
                      index_col="date",
                      na_values=['nan'],
                      parse_dates=True)
    dfSPY=dfSPY.rename(columns={'close':'spy'})
    df1=df1.join(dfSPY,how='inner')
    return df1

In [133]:
def get_data(symbols,dates):
    df1=get_base_dataframe(dates)
    for symbol in symbols:
        df_temp=pd.read_csv(symbol_to_path(symbol),
                          names=["date","sm1","open","high","low","close","volume"],
                          usecols=["date","close"],
                          index_col="date",
                          na_values=['nan'],
                          parse_dates=True)
        df_temp = df_temp.rename(columns={'close':symbol})
        df1=df1.join(df_temp)
    return df1

In [120]:
def plot_data(df,title="Stock prices"):
    ax = df.plot(title=title, fontsize=14)
    ax.set_xlabel("Date")
    ax.set_ylabel("Price")
    plt.show()

In [137]:
def plot_selected(df,symbols,start,end):
    df1=df.ix[start:end,symbols]
    ax = df1.plot(title="Plot Selected", fontsize=14)
    ax.set_xlabel("Date")
    ax.set_ylabel("Price")
    plt.show()

In [144]:
start='2006-03-01'
end='2016-04-01'
dates=pd.date_range(start,end)
get_data(['ibm','goog'],dates)
plot_selected(df1,['ibm','goog'],start,end)

In [103]:
for symbol in ["aapl","ibm"]:
    print(symbol)
    plot_historical(symbol)

aapl
      high      low
0  3.95098  3.28236
1  4.02635  3.69325
2  4.98432  3.58628
3  4.68040  4.20871
4  4.52965  4.11875
ibm
      high      low
0  43.9614  43.2834
1  44.4272  43.6744
2  44.5853  43.7784
3  43.6744  42.6886
4  43.8823  42.8176


In [10]:
tb=pd.read_csv("daily/table_{}.csv".format("aapl"))

In [147]:
import numpy as np

In [163]:
print(np.zeros((4,3,2),dtype=np.int))

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
